services:
  - type: web
    name: matchmovies
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "server.app:create_app()"
    envVars:
      - key: DATABASE_URL
        value: postgresql+psycopg://postgres:yYJDEM5ENvCMti3q@db.kwuxogvfhfgryiquhshl.supabase.co:5432/postgres?sslmode=require
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
